# Generated by Django 3.0.3 on 2020-02-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contacts', '0002_auto_20200224_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'bankAccounts'), ('model', 'nl_account')), models.Q(('app_label', 'bankAccounts'), ('model', 'us_account')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
