# Generated by Django 3.0.3 on 2020-02-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='NL_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('AccountNumber', models.CharField(max_length=32, verbose_name='Account Number')),
            ],
            options={
                'verbose_name': 'NL Bank Account',
            },
        ),
        migrations.CreateModel(
            name='US_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routingNumber', models.IntegerField(verbose_name='Routing Number')),
                ('accountNumber', models.IntegerField(verbose_name='Account Number')),
                ('accountType', models.CharField(choices=[('checkings', 'Checkings'), ('savings', 'Savings')], max_length=50, verbose_name='Account Type')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
            options={
                'verbose_name': 'US Bank Account',
            },
        ),
    ]
