# Generated by Django 3.0.3 on 2020-02-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nl_account',
            name='AccountNumber',
            field=models.CharField(max_length=34, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='nl_account',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='us_account',
            name='accountNumber',
            field=models.IntegerField(unique=True, verbose_name='Account Number'),
        ),
    ]
