# Generated by Django 3.0.3 on 2020-02-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(default='NaN', max_length=150)),
            ],
        ),
    ]
