# Generated by Django 3.0.3 on 2020-03-03 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[(1, 'Incasso'), (2, 'Batch payment'), (3, 'Batch payment'), (4, 'Branch withdrawal'), (5, 'Cash machine'), (6, 'Deposit'), (7, 'Online Banking'), (8, 'Payment terminal'), (9, 'SEPA direct debit'), (10, 'Sundries'), (11, 'Transfer')], max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
