# Generated by Django 3.0.3 on 2020-02-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[(1, 'Incasso'), (2, 'Batch payment'), (3, 'Batch payment'), (4, 'Branch withdrawal'), (5, 'Cash machine'), (6, 'Deposit'), (7, 'Online Banking'), (8, 'Payment terminal'), (9, 'SEPA direct debit'), (10, 'Sundries'), (11, 'Transfer')], max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
