# Generated by Django 3.0.3 on 2020-02-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=64)),
                ('dueDate', models.DateField(verbose_name='Due Date')),
                ('startDate', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
    ]
