# Generated by Django 3.0.3 on 2020-02-24 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='dueDate',
            field=models.DateField(blank=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
