# Generated by Django 3.0.3 on 2020-02-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0002_auto_20200224_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-amount']},
        ),
    ]
