# Generated by Django 3.0.3 on 2020-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fixedCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=99)),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='incomeFraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, unique=True)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=99, verbose_name='Allocation (%)')),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
