# Generated by Django 3.0.3 on 2020-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcharge',
            options={'ordering': ['-amount']},
        ),
        migrations.AlterField(
            model_name='fixedcharge',
            name='name',
            field=models.CharField(max_length=252, unique=True),
        ),
    ]
